# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('person_type', models.CharField(blank=True, max_length=100, null=True)),
                ('want', models.CharField(blank=True, max_length=1000, null=True)),
                ('reason', models.DateTimeField(auto_now=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
