# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_dream_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
