# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_dream_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=monitor.models.scramble_uploaded_filename),
        ),
        migrations.AlterField(
            model_name='dream',
            name='reason',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
