# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20171221_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='image',
            field=models.ImageField(blank=True, default='default', max_length=255, null=True, upload_to=monitor.models.scramble_uploaded_filename),
        ),
    ]
