# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20171221_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='image',
        ),
    ]
