# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_dream_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='dream',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dream',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dream',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
