# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_auto_20171225_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='want',
        ),
    ]
